name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]   # ya master, jo bhi tumhari default branch hai
  workflow_dispatch:     # Manual run ke liye bhi

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Full history chahiye
          lfs: true        # Agar large files hain to

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.Rvwaqas }}
        run: |
          git remote add hf https://huggingface.co/spaces/Rwaqas/todoapp
          
          git push -f hf main:main   # force push agar conflict ho