name: Sync Backend to Hugging Face Space

on:
  push:
    branches: [ main ]               # Ya jo tumhari default branch hai
    paths:
      - 'phase2/backend/**'          # Sirf backend folder change hone pe chalay
  workflow_dispatch:                 # Manual run ke liye

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Prepare backend as root
        run: |
          mkdir temp-backend
          mv phase2/backend/* temp-backend/
          rm -rf phase2                  # Cleanup (optional)
          mv temp-backend/* .
          rm -rf temp-backend

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.Rvwaqas }}
        run: |
          
          git add .
          git commit -m "Auto-sync backend from GitHub" || echo "No changes to commit"
          git push -f https://Rvwaqas:Rvwaqas@huggingface.co/spaces/Rvwaqas/todoapp HEAD:main
          # ↑ Yahan apna exact Space name daalo (Rvwaqas/todoapp ya jo bhi hai)
